# Generated by Django 2.2.5 on 2021-07-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
