# Generated by Django 2.2.5 on 2021-07-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0003_wish_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes_uploaded', to='wish_app.User'),
        ),
    ]
